### ISSUE TITLE
potential memory leak

### ISSUE THREAD

**Issue by Shortninja66** [Alexandeh/Glaedr#10]
you're storing player instances in a static collection and afaik you aren't removing them when the player quits (i haven't read that much of the code so i can be wrong). this can cause memory leaks if left untreated. don't make plugin developers do the work, it's an api not an spi

**Comment by bizarre** [comment]
Public version isn't up-to-date.
I can't be bothered pushing my current version to GitHub, consider this project abandoned.
Use at your own discretion.
