### ISSUE TITLE
Entries paused/saved on reboots and disconnects

### ISSUE THREAD

**Issue by Tr3xEmpire** [Alexandeh/Glaedr#8]
I would love a feature to save/pause all entries by default. My attempts seem really buggy and for some reason, it creates 3 of the same entry etc. Anyways, I'd love to see this as a base feature.

**Comment by bizarre** [comment]
This most likely won't happen because different people use different methods of saving. What do your attempts look like?

**Comment by Tr3xEmpire** [comment]
Currently, when a player logs out I just have their username and time left saved in a users file, but for whatever reason, when I log back in 3 of my timers are created and all their times reset.

**Comment by bizarre** [comment]
Here is how I accomplished my PvP protection functionality.
on entry tick, update profiles protection time
on leave, pause entry 
on disable, save profiles protection time (int)
on join (after restart), construct profile, check if saved int larger than 0 and if so send new entry with that time

**Comment by Tr3xEmpire** [comment]
Yeah I was trying to make a efficient pvp timer. So you're saying I should just pause the timer? What if the server reboots when a player is offline? Wouldn't that players entry be lost?

**Comment by Tr3xEmpire** [comment]
I just need an effective way to clear a players entries on leaving.
Suggestions?

**Comment by yaboicriminal** [comment]
PlayerScoreboard scoreboard = PlayerScoreboard.getScoreboard(player);
scoreboard.getEntries().clear();

^^
Worked for me when I was making mine.
